services:
  - type: web
    name: video-analyzer-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker fastapi_app:app

    packages:
      - ffmpeg

    envVars:
      - key: GOOGLE_API_KEY
        value: ""
      - key: TAVILY_API_KEY
        value: ""
