services:
  - type: web
    name: video-analyzer-api
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        value: ""
      - key: TAVILY_API_KEY
        value: ""
    dockerfilePath: ./Dockerfile
